### ISSUE TITLE
Update authenticated user profile details

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#139]
the current update user endpoint is vulnerable ie anyone can change user details. Needs a secured way to update user info

**Comment by BaharaJr** [comment]
Hello @bmsteven I changes updates on the user details to only use api/users without the ID <Here the user will only be editing their own details when logged in hence no one can change anyone's details>

**Comment by bmsteven** [comment]
Can we use passwords to update only email, username and password and update other details like dp, name etc without password? ?

**Comment by BaharaJr** [comment]
Yes we can

**Comment by bmsteven** [comment]
Okay great

**Comment by BaharaJr** [comment]
Hello boss @bmsteven can we close this?

**Comment by bmsteven** [comment]
Sure, it works perfectly fine now
