### ISSUE TITLE
Get user companies endpoint

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#70]
Getting all companies which user belongs either by creating a company or by being added by company creator @iam-budodi @erickmgongo

**Comment by BaharaJr** [comment]
You can also pass in company as field in users API to get all companies under the particular user

`api/users/<user ID>?fields=id,firstname,company`

**Comment by bmsteven** [comment]
> You can also pass in company as field in users API to get all companies under the particular user
> 
> `api/users/<user ID>?fields=id,firstname,company`

Ooh, didn't know this.. thanks. Looks like more are covered just missing in the documentation
