### ISSUE TITLE
Adding/update user and company profile endpoints

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#71]
User is expected to have several data ie dp, cv, title, bio, about, website... We expect to have add dp and add cv routes separately, and add profile route... This also means there is a need to add these data while fetching user.
Same goes for the company endpoint, we need company logo, email, about, bio as shown in the design @BaharaJr @iam-budodi @nab-in/backend

**Comment by BaharaJr** [comment]
Hello, @bmsteven may you please clarify this. Thank you.

**Comment by bmsteven** [comment]
> Hello, @bmsteven may you please clarify this. Thank you.

User and company will need additional profile information.
User should be able to upload their profile pictures and CV, also they should be able to add details about themselves such as bio, about, title(like a software developer), website etc as per design.

A company too needs a logo and some other info as per design

**Comment by bmsteven** [comment]
![Screenshot_20210701-130100](https://user-images.githubusercontent.com/48621248/124105971-70e04080-da6c-11eb-8c90-7aa49006f8e2.png)

I think these details are mentioned in readme
