### ISSUE TITLE
User settings endpoints

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#73]
User settings involves changing an email/username or password, these are critical user data so we need to verify user by kinda logging them again.
For email will require new email, current email/username and current password.
For username will require current email/username, new username and current password.
Same goes for password change will require current email/username, current password and new password

**Comment by bmsteven** [comment]
@iam-budodi @erickmgongo

**Comment by erickmgongo** [comment]
ill be dealing with this tomorrow hopefully

**Comment by bmsteven** [comment]
> ill be dealing with this tomorrow hopefully

Okay, thanks
