### ISSUE TITLE
Adding jobs with categories and the other keys

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#74]
We need to upload job details with several important keys, 
1. company id( i guess it's already taken care of)
2. Open to, this is important key to identify whether job is open to companies/individual and whether its freelance/full time
3. Email. If a company has email, it will be used here and if not, user needs to add it
4. Job document (pdf)
5. Categories (user should be able to add categories and subcategories while adding a job
6. Deadline date and deadline time
7. Others I think they already done..

...this should apply to edit job except the company details

**Comment by BaharaJr** [comment]
Hello @bmsteven I think if you look at the job profile in the documentation, we already have closedate for the deadline and that is date time field

**Comment by BaharaJr** [comment]
And you can also create jobs with categories(categories come with subcategories so just category id is enough)

{
    "description":"description",
    "name": "description",
    "company":{"id": "Hp5evOlVV9C8O"},
    "categories": [{"id":"Ywl9Qsgd2uOXe"}]
}

**Comment by BaharaJr** [comment]
Hello @bmsteven if I have answered all your questions, please go ahead and close the issue. Otherwise I am realizing we need to update the documentation.

**Comment by bmsteven** [comment]
> Hello @bmsteven I think if you look at the job profile in the documentation, we already have closedate for the deadline and that is date time field

The doc doesn't have all these, am not sure which key I should pass in request body for them dates
Also don't know if it accepts open to key and job document key? I think if all of these are covered, we can close the issue... Thanks

**Comment by BaharaJr** [comment]
Hello @bmsteven I updated jobs documentation to add all required properties in the table, please review and let me know if it suffices our need?
