### ISSUE TITLE
Check if user belongs to a company endpoint

### ISSUE THREAD

**Issue by bmsteven** [nab-in/portal-backend#76]
Checking if user with a token belongs to a certain company with id

**Comment by BaharaJr** [comment]
This can be done @iam-budodi or @erickmgongo if any of you guys can jump on this, let's catch up if you need some help.

**Comment by erickmgongo** [comment]
**On it**, so @bmsteven  can i get sample request body and response you want from this endpoint

**Comment by bmsteven** [comment]
> **On it**, so @bmsteven can i get sample request body and response you want from this endpoint

I will be sending a token in headers and company id in the request body say 
{
  company: ddfgv457_$
}

**Comment by bmsteven** [comment]
The response can be true or false I guess

**Comment by erickmgongo** [comment]
@BaharaJr please review the pull request and merge if everything is fine, so @bmsteven can close this issue.

**Comment by BaharaJr** [comment]
Hello @erickmgongo I am on it, will review and  accept the PR
